### ISSUE TITLE
Kanto Safari Zone bug when click Help

### ISSUE THREAD

**Issue by yosiam** [pokeclicker-dev/pokeclicker#115]
When you are at Kanto Safari Zone and click in Help button it doesn't load nothing and doesn't let to move anymore at Safari forcing you to reload the game and pay again the entrance

**Comment by Aegyo** [comment]
I've just tried this myself and couldn't get the issue to happen. In fact I could still move around in the safari while on the Help tab and trigger battles. Moving around the safari continued working when switching back to Explore.

Can you give any more information to help reproduce this? (eg, browser and browser version, any messages in F12 dev console, if you have to try clicking the help tab in a specific situation)

**Comment by RedSparr0w** [comment]
Unable to reproduce, no new info, closed.
