### ISSUE TITLE
Dock won't open.

### ISSUE THREAD

**Issue by FloofyBird** [pokeclicker-dev/pokeclicker#88]
**Info**
 - OS: [e.g. Windows 10]
 - Crome
 - v0.4.19

**Description:**

I have 151 pokemon, and event pokemon, but the dock is still closed.
**Steps to Reproduce:**

**Expected Behavior:**

I expected to have the dock open.
**Screenshots:**

**Additional Information:**

**Comment by RedSparr0w** [comment]
You need to go to the starter town and it will allow you to travel regions
